-- Axis
-- SPDX-License-Identifier: LGPL-2.1-or-later
-- Copyright (C) 2026 the Axis contributors

-- Что делает настройка и во что она обходится.
--
-- Родные описания движка писались как подсказки для тех, кто и так знает
-- устройство: строка-другая, без единого слова о цене. В меню же читает игрок,
-- которому нужно решить, чем пожертвовать ради частоты кадров, — поэтому здесь
-- у каждой настройки сказано и что она меняет, и сколько это стоит.
--
-- Поле load — требовательность: high, medium, low. Её меню дописывает
-- отдельной строкой и красит, чтобы уровень был виден, не читая текста.
-- Настройке, которая ничего не стоит, поле не нужно.

-- Пометка для перевода, а не сам перевод. Этот файл читается один раз за
-- запуск, а язык меняют когда угодно; переведи здесь — и после смены языка
-- пояснения остались бы на прежнем. Переводит их тот, кто собирает строку
-- настройки (get_description в components.lua).
local function N_(text)
	return text
end

return {
	["3d_mode"] = { text = N_("Stereo picture for 3D glasses or a split screen. Anything except «none» draws the world twice and roughly halves the frame rate."), load = "high" },
	["3d_paralax_strength"] = { text = N_("How far apart the two pictures are in 3D mode. Changes how deep the picture feels.") },
	["abm_interval"] = { text = N_("How often the world's own rules run: grass spreading, water flowing, fire burning."), load = "high" },
	["abm_time_budget"] = { text = N_("How much of each turn those rules may take. Less means a smoother server and slower world."), load = "high" },
	["active_block_mgmt_interval"] = { text = N_("How often the server checks which parts of the world are alive.") },
	["active_block_range"] = { text = N_("How far around each player the world stays alive: plants grow, machines work. The heaviest server setting there is."), load = "high" },
	["active_object_send_range_blocks"] = { text = N_("How far away creatures and moving things are still sent to the player."), load = "medium" },
	["always_fly_fast"] = { text = N_("Always fly at full speed, without holding the fast key.") },
	["ambient_occlusion_gamma"] = { text = N_("How dark the corners between blocks look. Higher means softer shading in the corners.") },
	["anisotropic_filter"] = { text = N_("Keep textures sharp on surfaces you see edge-on, like a floor stretching away. Cheap and noticeable."), load = "medium" },
	["antialiasing"] = { text = N_("How the jagged staircase edges are smoothed. FSAA is the cleanest and the heaviest, FXAA is almost free but slightly blurry."), load = "medium" },
	["anticheat_flags"] = { text = N_("Which kinds of cheating the server watches for."), load = "low" },
	["anticheat_movement_tolerance"] = { text = N_("How far a player may drift from where the server thinks they are before it counts as cheating. Raise it if honest players on a poor connection get caught.") },
	["arm_inertia"] = { text = N_("Let the item in your hand swing a little behind the camera when you turn. Just for looks.") },
	["array_texture_max"] = { text = N_("How many textures the game keeps in one bundle for the graphics card. Bigger bundles draw faster."), load = "low" },
	["ask_reconnect_on_crash"] = { text = N_("Offer players to come back after a crash.") },
	["autojump"] = { text = N_("Step up single blocks automatically, without pressing jump.") },
	["autosave_screensize"] = { text = N_("Remember the window size, so next time the game opens exactly as you left it.") },
	["autoscale_mode"] = { text = N_("Stretch small textures to the size of the block automatically.") },
	["aux1_descends"] = { text = N_("Make the special key move you down while flying or climbing, instead of doing what it usually does.") },
	["basic_privs"] = { text = N_("Which rights a moderator may hand out to others.") },
	["bilinear_filter"] = { text = N_("Smooth textures when you stand close to them. Some like it, some prefer sharp pixels."), load = "low" },
	["bind_address"] = { text = N_("Which network address the server listens on. Empty means all of them.") },
	["block_cull_optimize_distance"] = { text = N_("From what distance that skipping becomes rougher and cheaper.") },
	["block_send_optimize_distance"] = { text = N_("From what distance the server starts sending the world more sparingly.") },
	["camera_smoothing"] = { text = N_("How softly the camera follows your mouse. Higher makes the view smoother and a little slower to respond.") },
	["chat_font_size"] = { text = N_("Size of the chat text. Zero means the usual size.") },
	["chat_log_level"] = { text = N_("Which messages also appear in the in-game chat.") },
	["chat_message_format"] = { text = N_("How a chat line is built: where the name goes, where the text goes.") },
	["chat_message_limit_per_10sec"] = { text = N_("How many messages one player may send in ten seconds before being told to slow down.") },
	["chat_message_limit_trigger_kick"] = { text = N_("After how many messages over the limit a player is kicked off the server.") },
	["chat_message_max_size"] = { text = N_("The longest message a player may send. Longer ones are cut.") },
	["chat_weblink_color"] = { text = N_("Colour of clickable links in chat.") },
	["chatcommand_msg_time_threshold"] = { text = N_("How long a command may take before the server says it is still working on it.") },
	["chunksize"] = { text = N_("How large a piece of world is created at once. Bigger pieces generate faster overall and cause longer pauses."), load = "medium" },
	["cinematic_camera_smoothing"] = { text = N_("The same softness, but for cinematic mode, where the camera is meant to glide.") },
	["clickable_chat_weblinks"] = { text = N_("Make links in chat clickable.") },
	["client_mapblock_limit"] = { text = N_("How many pieces of the world are kept in memory at once. Fewer means less memory and more reloading."), load = "medium" },
	["client_mesh_chunk"] = { text = N_("How large a piece of the world is prepared at once. Larger pieces draw faster and take longer to rebuild after you place a block."), load = "medium" },
	["client_unload_unused_data_timeout"] = { text = N_("How long the game keeps parts of the world you have left before forgetting them, in seconds.") },
	["cloud_radius"] = { text = N_("How far the flat clouds spread around you."), load = "medium" },
	["connected_glass"] = { text = N_("Join glass blocks placed next to each other into one clean pane, without lines between them."), load = "low" },
	["console_alpha"] = { text = N_("How solid the chat console background is.") },
	["console_color"] = { text = N_("Background colour of the chat console.") },
	["console_height"] = { text = N_("How much of the screen the chat console takes when opened.") },
	["contentdb_enable_updates_indicator"] = { text = N_("Show a mark when an installed add-on has a newer version.") },
	["contentdb_flag_blacklist"] = { text = N_("Hide content marked with these flags, such as adult or non-free.") },
	["contentdb_max_concurrent_downloads"] = { text = N_("How many add-ons may download at the same time.") },
	["contentdb_url"] = { text = N_("Where the game looks for downloadable content.") },
	["crosshair_alpha"] = { text = N_("How visible the crosshair is. Zero hides it completely.") },
	["nametag_max_visible"] = { text = N_("How many names may hang over players at once. The ones nearest to the crosshair win; the rest are not drawn. Zero means no limit.") },
	["crosshair_color"] = { text = N_("Colour of the crosshair in the middle of the screen.") },
	["crosshair_dot"] = { text = N_("A dot in the very middle, on top of whatever shape is chosen. Zero for none.") },
	["crosshair_gap"] = { text = N_("How far the strokes start from the middle. A wider gap leaves the target itself uncovered.") },
	["crosshair_object_color"] = { text = N_("Colour the crosshair turns while it points at a player or a creature.") },
	["crosshair_outline"] = { text = N_("Dark outline around the crosshair. Helps it stand out against snow and sky, but thickens the strokes.") },
	["crosshair_outline_alpha"] = { text = N_("How visible the outline is.") },
	["crosshair_outline_color"] = { text = N_("Colour of the outline. Black reads best on a light background.") },
	["crosshair_shape"] = { text = N_("What the crosshair is built from: a cross, a diagonal cross, a dot, a ring, a frame, corner brackets — or nothing at all.") },
	["crosshair_size"] = { text = N_("Length of each stroke, and the size of the dot for the dot shape.") },
	["crosshair_thickness"] = { text = N_("How thick the crosshair lines are.") },
	["csm_restriction_flags"] = { text = N_("What client-side mods are forbidden to do on this server.") },
	["csm_restriction_noderange"] = { text = N_("How far around the player client-side mods may look at the world.") },
	["curl_file_download_timeout"] = { text = N_("The same limit for large files.") },
	["curl_parallel_limit"] = { text = N_("How many downloads may run at the same time.") },
	["curl_timeout"] = { text = N_("How long a download may take before it is called failed.") },
	["debanding"] = { text = N_("Remove the ugly stripes that show up on smooth gradients, like the evening sky."), load = "low" },
	["debug_log_level"] = { text = N_("How much detail goes into the log file. More detail helps find problems and makes the file grow fast."), load = "low" },
	["debug_log_size_max"] = { text = N_("How big one log may grow before it is put into the archive and a fresh one started, in megabytes. Every run gets its own file anyway — this matters to a server that runs for weeks without a restart.") },
	["dedicated_server_step"] = { text = N_("How often the server sends changes to players. Smaller means smoother play and more work for the server."), load = "high" },
	["default_password"] = { text = N_("The password new accounts get. Empty means anyone may join without one.") },
	["default_privs"] = { text = N_("What a new player is allowed to do.") },
	["default_stack_max"] = { text = N_("How many identical items fit in one slot.") },
	["deprecated_lua_api_handling"] = { text = N_("What to do when a mod uses an outdated feature: keep quiet, warn, or stop.") },
	["directional_colored_fog"] = { text = N_("Colour the haze like the sky in the direction you are looking. Sunsets look much better with it."), load = "low" },
	["disallow_empty_password"] = { text = N_("Do not let players keep an empty password.") },
	["display_density_factor"] = { text = N_("How dense your screen is. Affects how big everything looks; usually best left alone.") },
	["display_gamma"] = { text = N_("Overall brightness of the picture. Raise it if dark places are too dark to see anything.") },
	["doubletap_jump"] = { text = N_("Turn flying on and off by tapping jump twice.") },
	["emergequeue_limit_diskonly"] = { text = N_("How many of them may be read from disk at a time.") },
	["emergequeue_limit_generate"] = { text = N_("How many of them may be created from scratch at a time."), load = "medium" },
	["emergequeue_limit_total"] = { text = N_("How many pieces of the world may wait in line to be loaded or created.") },
	["enable_3d_clouds"] = { text = N_("Make clouds solid instead of a flat sheet. They look much better from below and while flying."), load = "low" },
	["enable_all_mods"] = { text = N_("Turn on every mod of the crate, ignoring what the world has enabled.") },
	["enable_auto_exposure"] = { text = N_("Let your eyes adjust: step out of a cave and the light slowly settles down, just like in life."), load = "low" },
	["enable_bloom"] = { text = N_("Let bright things glow softly around themselves, like the sun through leaves."), load = "medium" },
	["enable_bloom_debug"] = { text = N_("Show the glow effect split into its parts. For those tuning it.") },
	["enable_build_where_you_stand"] = { text = N_("Allow placing blocks in the space you are standing in.") },
	["enable_client_modding"] = { text = N_("Allow mods that run on your own computer."), load = "low" },
	["enable_console"] = { text = N_("Show a separate console window next to the game. Windows only.") },
	["enable_dynamic_shadows"] = { text = N_("Let the sun and moon cast real shadows. This is the most beautiful and the heaviest effect in the game: expect to lose a noticeable part of your frames."), load = "high" },
	["enable_esc_dialog"] = { text = N_("Ask before leaving the game when you press escape.") },
	["enable_fog"] = { text = N_("Fade the far edge of the world into a haze, instead of showing where the world simply stops."), load = "low" },
	["enable_hotbar_mouse_wheel"] = { text = N_("Switch the item in your hand with the mouse wheel.") },
	["enable_ipv6"] = { text = N_("Allow IPv6 connections at all.") },
	["enable_local_map_saving"] = { text = N_("Keep the parts of the world you have seen on a server, so they load from your disk next time."), load = "low" },
	["enable_mapgen_debug_info"] = { text = N_("Write technical details about world generation to the log.") },
	["enable_mod_channels"] = { text = N_("Let mods talk to each other over their own channels.") },
	["enable_post_processing"] = { text = N_("The master switch for the finishing touches: glow, tone, exposure. With it off none of them cost anything."), load = "medium" },
	["enable_raytraced_culling"] = { text = N_("Check more carefully what is hidden behind walls. Fewer invisible blocks get drawn, but the checking itself takes some work."), load = "medium" },
	["enable_remote_media_server"] = { text = N_("Let clients fetch textures and sounds from the address given above.") },
	["enable_rollback_recording"] = { text = N_("Record who changed what, so damage can be undone later. Costs disk space and some speed."), load = "medium" },
	["enable_split_login_register"] = { text = N_("Ask separately whether you are logging in or registering a new account.") },
	["enable_sscsm"] = { text = N_("Allow the server to send mods that run on your computer.") },
	["enable_translucent_foliage"] = { text = N_("Let sunlight shine through leaves so they glow when the sun is behind them."), load = "low" },
	["enable_volumetric_clouds"] = { text = N_("Replace flat clouds with real ones you can fly through. Very beautiful and very heavy."), load = "high" },
	["enable_volumetric_lighting"] = { text = N_("Draw sunbeams in the air. Best seen when you look towards the sun."), load = "medium" },
	["enable_water_reflections"] = { text = N_("Reflect the sky and the shore in the water."), load = "medium" },
	["enable_waving_leaves"] = { text = N_("Let leaves sway in the wind. Pretty, and a little heavier in a thick forest."), load = "medium" },
	["enable_waving_plants"] = { text = N_("Let grass and flowers sway in the wind."), load = "medium" },
	["enable_waving_water"] = { text = N_("Let the water surface move in waves instead of lying flat like glass."), load = "medium" },
	["exposure_compensation"] = { text = N_("Make the whole picture brighter or darker.") },
	["fallback_font_path"] = { text = N_("The font used for letters the main font does not have — Chinese or Japanese, for example.") },
	["fixed_map_seed"] = { text = N_("The number a world is built from. The same number always gives the same world; empty means a new one each time.") },
	["fixed_virtual_joystick"] = { text = N_("Keep the on-screen stick in one place instead of putting it where you touch.") },
	["fog_start"] = { text = N_("How close the haze begins. Closer haze hides the distance, but the game still draws what is behind it.") },
	["font_bold"] = { text = N_("Use the bold face for all text.") },
	["font_italic"] = { text = N_("Use the italic face for all text.") },
	["font_path"] = { text = N_("Which font file the game uses for ordinary text.") },
	["font_path_bold"] = { text = N_("Font file for bold text.") },
	["font_path_bold_italic"] = { text = N_("Font file for bold italic text.") },
	["font_path_italic"] = { text = N_("Font file for italic text.") },
	["font_shadow"] = { text = N_("How far the shadow under the letters is offset. Makes text readable on a light background.") },
	["font_shadow_alpha"] = { text = N_("How dark that shadow is.") },
	["font_size"] = { text = N_("Size of the main text in the game.") },
	["font_size_divisible_by"] = { text = N_("Round the font size to a multiple of this number. For pixel fonts, so they stay crisp.") },
	["formspec_fullscreen_bg_color"] = { text = N_("Colour of that dimming.") },
	["formspec_fullscreen_bg_opacity"] = { text = N_("How much the game behind a fullscreen window is dimmed.") },
	["fov"] = { text = N_("How wide a view you have. A wider view shows more around you, but the game has to draw more of the world at once."), load = "medium" },
	["fps_max"] = { text = N_("The highest number of frames per second the game will draw. Extra frames you cannot see anyway only heat up the computer, so a limit near your monitor's refresh rate is a good idea."), load = "low" },
	["fps_max_unfocused"] = { text = N_("Frame limit while the game window is in the background. Keep it low so the game does not eat the computer while you are doing something else."), load = "low" },
	["fsaa"] = { text = N_("How thoroughly the edges are smoothed. Every step up is much heavier for the graphics card: four times means about four times the work on the world."), load = "high" },
	["full_block_send_enable_min_time_from_building"] = { text = N_("How long after building the server waits before sending whole pieces of the world again.") },
	["fullscreen"] = { text = N_("Play on the whole screen instead of in a window. Usually a bit smoother than a window of the same size."), load = "low" },
	["fxaa"] = { text = N_("Smooth the edges after the frame is drawn. Costs almost nothing, but small details get a little soft."), load = "low" },
	["gui_scaling"] = { text = N_("How big menus and windows are. Raise it if the text is too small on a big screen."), load = "low" },
	["gui_scaling_filter"] = { text = N_("Smooth interface pictures when they are stretched. Turn it off if you like sharp pixels."), load = "low" },
	["hud_hotbar_max_width"] = { text = N_("How wide the hotbar is allowed to be, as a share of the screen.") },
	["hud_scaling"] = { text = N_("How big the on-screen indicators are: health, hotbar, and the rest.") },
	["hurt_flash_enabled"] = { text = N_("Flash the screen red when you get hurt, so you notice it even in a fight.") },
	["ignore_world_load_errors"] = { text = N_("Enter the world even if part of it failed to load. Dangerous: the damage may spread.") },
	["inventory_items_animations"] = { text = N_("Let animated blocks keep moving inside the inventory as well."), load = "low" },
	["invert_hotbar_mouse_wheel"] = { text = N_("Reverse the direction the wheel switches items in.") },
	["invert_mouse"] = { text = N_("Turn the vertical mouse movement upside down.") },
	["ipv6_server"] = { text = N_("Let the server accept connections over IPv6 as well.") },
	["item_entity_ttl"] = { text = N_("How long a dropped item lies on the ground before it disappears, in seconds.") },
	["joystick_frustum_sensitivity"] = { text = N_("How fast the view turns with the gamepad stick.") },
	["joystick_inner_deadzone"] = { text = N_("How far the stick must move before the game notices. Raise it if the view drifts on its own.") },
	["joystick_outer_deadzone"] = { text = N_("How close to the edge the stick counts as fully pushed.") },
	["keyboard_camera_speed"] = { text = N_("How fast the view turns when you look around with the keyboard.") },
	["keymap_aux1"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_backward"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_camera_mode"] = { text = N_("Switch between first person and the view from behind.") },
	["keymap_camera_pitch_down"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_camera_pitch_up"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_camera_yaw_left"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_camera_yaw_right"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_chat"] = { text = N_("Open the chat line.") },
	["keymap_cinematic"] = { text = N_("Smooth camera mode, for recording video.") },
	["keymap_close_world"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_cmd"] = { text = N_("Open the chat line with a command already started.") },
	["keymap_cmd_local"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_console"] = { text = N_("Open the large chat console.") },
	["keymap_decrease_viewing_range_min"] = { text = N_("See less far, and get some frames back.") },
	["keymap_decrease_volume"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_dig"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_drop"] = { text = N_("Drop the item you are holding.") },
	["keymap_fastmove"] = { text = N_("Move fast, if the server allows it.") },
	["keymap_forward"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_freemove"] = { text = N_("Fly, if the server allows it.") },
	["keymap_fullscreen"] = { text = N_("Switch between window and fullscreen.") },
	["keymap_help"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_hotbar_next"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_hotbar_previous"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_increase_viewing_range_min"] = { text = N_("See further. Beyond a point this costs frames.") },
	["keymap_increase_volume"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_inventory"] = { text = N_("Open your inventory.") },
	["keymap_jump"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_left"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_minimap"] = { text = N_("Show the small map in the corner of the screen.") },
	["keymap_mute"] = { text = N_("Turn the sound off and on.") },
	["keymap_noclip"] = { text = N_("Walk through walls, if the server allows it.") },
	["keymap_pause"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_pickitem"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_pitchmove"] = { text = N_("Fly in the direction you are looking, rather than straight ahead.") },
	["keymap_place"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_quicktune_dec"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_quicktune_inc"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_quicktune_next"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_quicktune_prev"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_rangeselect"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_right"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_screenshot"] = { text = N_("Take a picture of the screen and save it to the screenshots folder.") },
	["keymap_slot1"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_slot10"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_slot11"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_slot12"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_slot13"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_slot14"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_slot15"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_slot16"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_slot17"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_slot18"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_slot19"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_slot2"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_slot20"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_slot21"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_slot22"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_slot23"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_slot24"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_slot25"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_slot26"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_slot27"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_slot28"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_slot29"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_slot3"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_slot30"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_slot31"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_slot32"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_slot4"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_slot5"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_slot6"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_slot7"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_slot8"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_slot9"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_sneak"] = { text = N_("Move slowly and carefully. While sneaking you will not step off the edge of a block.") },
	["keymap_sprint"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_toggle_block_bounds"] = { text = N_("Show the grid the world is divided into. Useful for building and for understanding what the server sends you.") },
	["keymap_toggle_chat"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_toggle_debug"] = { text = N_("Show the technical information panel.") },
	["keymap_toggle_fog"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_toggle_hud"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_toggle_profiler"] = { text = N_("Show where the game's time goes. For finding what makes it stutter.") },
	["keymap_toggle_update_camera"] = { text = N_("Which key does this. Click the setting and press the key you want.") },
	["keymap_zoom"] = { text = N_("Look into the distance, as through binoculars. The server may forbid it.") },
	["kick_msg_crash"] = { text = N_("What players are told when the server falls over.") },
	["kick_msg_shutdown"] = { text = N_("What players are told when the server shuts down normally.") },
	["language"] = { text = N_("The language of the game. «System language» takes the one your computer uses.") },
	["leaves_style"] = { text = N_("How leaves are drawn. «Fancy» looks like real foliage, «simple» is lighter, and «opaque» turns leaves into solid blocks — the fastest by far. In a forest the difference is very noticeable."), load = "medium" },
	["lighting_alpha"] = { text = N_("How dark the darkest places are.") },
	["lighting_beta"] = { text = N_("How bright the brightest places are.") },
	["lighting_boost"] = { text = N_("Extra light added around a chosen brightness.") },
	["lighting_boost_center"] = { text = N_("Which brightness gets that extra light.") },
	["lighting_boost_spread"] = { text = N_("How wide a range of brightness the addition covers.") },
	["liquid_loop_max"] = { text = N_("How many liquid updates the server does in one go."), load = "medium" },
	["liquid_queue_purge_time"] = { text = N_("How long the liquid queue may grow before it is cleared. Zero never clears it.") },
	["liquid_update"] = { text = N_("How often liquids flow, in seconds. Smaller makes water livelier and the server busier."), load = "high" },
	["main_menu_script"] = { text = N_("A script that replaces the main menu. For those building their own.") },
	["main_world_name"] = { text = N_("Which world opens by default.") },
	["map_compression_level_disk"] = { text = N_("How hard the world is squeezed when saved to disk."), load = "medium" },
	["map_compression_level_net"] = { text = N_("How hard the world is squeezed before being sent. Harder saves traffic and costs processor time."), load = "medium" },
	["mapgen_limit"] = { text = N_("How far the world reaches before it simply ends.") },
	["max_block_generate_distance"] = { text = N_("How far from the player new world may still be generated."), load = "high" },
	["max_block_send_distance"] = { text = N_("How far the server sends pieces of the world at all."), load = "medium" },
	["max_clearobjects_extra_loaded_blocks"] = { text = N_("How many extra pieces of the world may be loaded at once while cleaning up objects.") },
	["max_forceloaded_blocks"] = { text = N_("How many pieces of the world mods may keep loaded even with nobody nearby.") },
	["max_objects_per_block"] = { text = N_("How many things may pile up in one piece of the world. A limit against dropped items flooding the server."), load = "medium" },
	["max_out_chat_queue_size"] = { text = N_("How many chat messages may wait in line before the oldest are dropped.") },
	["max_packets_per_iteration"] = { text = N_("How many network packets the server handles in one go.") },
	["max_simultaneous_block_sends_per_client"] = { text = N_("How many pieces of the world the server sends one player at a time.") },
	["max_users"] = { text = N_("How many players may be on the server at once.") },
	["menu_clouds"] = { text = N_("Show moving clouds behind the main menu."), load = "low" },
	["menu_theme"] = { text = N_("Which look the main menu uses.") },
	["mesh_buffer_min_vertices"] = { text = N_("How small a piece of the world may be before it is merged with its neighbours. Merging makes drawing cheaper."), load = "low" },
	["mesh_generation_interval"] = { text = N_("How often the game rebuilds the pieces of the world it draws."), load = "low" },
	["mesh_generation_threads"] = { text = N_("How many processor cores prepare the world for drawing. More cores mean less stutter when the world loads."), load = "low" },
	["mg_biome_np_heat"] = { text = N_("How warmth is spread over the world — it decides where deserts and snow end up.") },
	["mg_biome_np_heat_blend"] = { text = N_("How softly neighbouring warm and cold areas blend into each other.") },
	["mg_biome_np_humidity"] = { text = N_("How dampness is spread over the world — it decides where swamps and dry lands go.") },
	["mg_biome_np_humidity_blend"] = { text = N_("How softly damp and dry areas blend into each other.") },
	["mg_flags"] = { text = N_("What is made in the world at all: caves, dungeons, trees, ores, lakes.") },
	["mg_name"] = { text = N_("Which mapgen builds the world: hills and caves, flat ground, floating islands.") },
	["mgcarpathian_base_level"] = { text = N_("The height the landscape is built around.") },
	["mgcarpathian_cave_width"] = { text = N_("How wide the cave tunnels are.") },
	["mgcarpathian_cavern_limit"] = { text = N_("Above this height the huge underground halls do not appear.") },
	["mgcarpathian_cavern_taper"] = { text = N_("The height at which those halls start to thin out.") },
	["mgcarpathian_cavern_threshold"] = { text = N_("How often the huge halls turn up. Lower means more of them.") },
	["mgcarpathian_dungeon_ymax"] = { text = N_("Above this height there are no dungeons.") },
	["mgcarpathian_dungeon_ymin"] = { text = N_("Below this height there are no dungeons.") },
	["mgcarpathian_large_cave_depth"] = { text = N_("Below this height the big caves begin.") },
	["mgcarpathian_large_cave_flooded"] = { text = N_("What share of the big caves is flooded with water.") },
	["mgcarpathian_large_cave_num_max"] = { text = N_("The most big caves in one piece of the world.") },
	["mgcarpathian_large_cave_num_min"] = { text = N_("The fewest big caves in one piece of the world.") },
	["mgcarpathian_np_cave1"] = { text = N_("How the cave tunnels wind.") },
	["mgcarpathian_np_cave2"] = { text = N_("The second set of tunnels, crossing the first.") },
	["mgcarpathian_np_cavern"] = { text = N_("Where the huge underground halls are.") },
	["mgcarpathian_np_dungeons"] = { text = N_("Where dungeons turn up.") },
	["mgcarpathian_np_filler_depth"] = { text = N_("How thick the soil lying on the stone is.") },
	["mgcarpathian_np_height1"] = { text = N_("The first layer of the landscape's height.") },
	["mgcarpathian_np_height2"] = { text = N_("The second layer of the landscape's height.") },
	["mgcarpathian_np_height3"] = { text = N_("The third layer of the landscape's height.") },
	["mgcarpathian_np_height4"] = { text = N_("The fourth layer of the landscape's height.") },
	["mgcarpathian_np_hills"] = { text = N_("The shape of the hills.") },
	["mgcarpathian_np_hills_terrain"] = { text = N_("Where the hilly country is.") },
	["mgcarpathian_np_mnt_var"] = { text = N_("How much the mountains differ from one another.") },
	["mgcarpathian_np_ridge_mnt"] = { text = N_("The shape of the ridges.") },
	["mgcarpathian_np_ridge_terrain"] = { text = N_("Where the ridges are.") },
	["mgcarpathian_np_rivers"] = { text = N_("Where rivers run.") },
	["mgcarpathian_np_step_mnt"] = { text = N_("The shape of the steps.") },
	["mgcarpathian_np_step_terrain"] = { text = N_("Where the stepped country is.") },
	["mgcarpathian_river_depth"] = { text = N_("How deep the rivers cut into the land.") },
	["mgcarpathian_river_width"] = { text = N_("How wide the rivers are.") },
	["mgcarpathian_small_cave_num_max"] = { text = N_("The most small caves in one piece of the world.") },
	["mgcarpathian_small_cave_num_min"] = { text = N_("The fewest small caves in one piece of the world.") },
	["mgcarpathian_spflags"] = { text = N_("What the Carpathian mapgen makes: caves, dungeons, rivers, floating islands and the rest.") },
	["mgcarpathian_valley_width"] = { text = N_("How wide the valleys are.") },
	["mgflat_cave_width"] = { text = N_("How wide the cave tunnels are.") },
	["mgflat_cavern_limit"] = { text = N_("Above this height the huge underground halls do not appear.") },
	["mgflat_cavern_taper"] = { text = N_("The height at which those halls start to thin out.") },
	["mgflat_cavern_threshold"] = { text = N_("How often the huge halls turn up. Lower means more of them.") },
	["mgflat_dungeon_ymax"] = { text = N_("Above this height there are no dungeons.") },
	["mgflat_dungeon_ymin"] = { text = N_("Below this height there are no dungeons.") },
	["mgflat_ground_level"] = { text = N_("The height of the flat ground.") },
	["mgflat_hill_steepness"] = { text = N_("How steep those hills are.") },
	["mgflat_hill_threshold"] = { text = N_("How often hills rise out of the flat ground. Lower means more of them.") },
	["mgflat_lake_steepness"] = { text = N_("How steep the banks of those lakes are.") },
	["mgflat_lake_threshold"] = { text = N_("How often lakes appear in the flat ground. Lower means more of them.") },
	["mgflat_large_cave_depth"] = { text = N_("Below this height the big caves begin.") },
	["mgflat_large_cave_flooded"] = { text = N_("What share of the big caves is flooded with water.") },
	["mgflat_large_cave_num_max"] = { text = N_("The most big caves in one piece of the world.") },
	["mgflat_large_cave_num_min"] = { text = N_("The fewest big caves in one piece of the world.") },
	["mgflat_np_cave1"] = { text = N_("How the cave tunnels wind.") },
	["mgflat_np_cave2"] = { text = N_("The second set of tunnels, crossing the first.") },
	["mgflat_np_cavern"] = { text = N_("Where the huge underground halls are.") },
	["mgflat_np_dungeons"] = { text = N_("Where dungeons turn up.") },
	["mgflat_np_filler_depth"] = { text = N_("How thick the soil lying on the stone is.") },
	["mgflat_np_terrain"] = { text = N_("The shape of the landscape.") },
	["mgflat_small_cave_num_max"] = { text = N_("The most small caves in one piece of the world.") },
	["mgflat_small_cave_num_min"] = { text = N_("The fewest small caves in one piece of the world.") },
	["mgflat_spflags"] = { text = N_("What the Flat mapgen makes: caves, dungeons, rivers, floating islands and the rest.") },
	["mgfractal_cave_width"] = { text = N_("How wide the cave tunnels are.") },
	["mgfractal_dungeon_ymax"] = { text = N_("Above this height there are no dungeons.") },
	["mgfractal_dungeon_ymin"] = { text = N_("Below this height there are no dungeons.") },
	["mgfractal_fractal"] = { text = N_("Which mathematical shape the world is built from. Each gives a completely different landscape.") },
	["mgfractal_iterations"] = { text = N_("How finely that shape is worked out. More means finer detail and slower generation."), load = "medium" },
	["mgfractal_julia_w"] = { text = N_("Fourth number of the Julia shape.") },
	["mgfractal_julia_x"] = { text = N_("First number of the Julia shape.") },
	["mgfractal_julia_y"] = { text = N_("Second number of the Julia shape.") },
	["mgfractal_julia_z"] = { text = N_("Third number of the Julia shape.") },
	["mgfractal_large_cave_depth"] = { text = N_("Below this height the big caves begin.") },
	["mgfractal_large_cave_flooded"] = { text = N_("What share of the big caves is flooded with water.") },
	["mgfractal_large_cave_num_max"] = { text = N_("The most big caves in one piece of the world.") },
	["mgfractal_large_cave_num_min"] = { text = N_("The fewest big caves in one piece of the world.") },
	["mgfractal_np_cave1"] = { text = N_("How the cave tunnels wind.") },
	["mgfractal_np_cave2"] = { text = N_("The second set of tunnels, crossing the first.") },
	["mgfractal_np_dungeons"] = { text = N_("Where dungeons turn up.") },
	["mgfractal_np_filler_depth"] = { text = N_("How thick the soil lying on the stone is.") },
	["mgfractal_np_seabed"] = { text = N_("The shape of the sea floor.") },
	["mgfractal_offset"] = { text = N_("Where the shape sits in the world.") },
	["mgfractal_scale"] = { text = N_("How large the shape is in the world.") },
	["mgfractal_slice_w"] = { text = N_("Which slice of the shape becomes the world. Change it for a completely different landscape from the same shape.") },
	["mgfractal_small_cave_num_max"] = { text = N_("The most small caves in one piece of the world.") },
	["mgfractal_small_cave_num_min"] = { text = N_("The fewest small caves in one piece of the world.") },
	["mgfractal_spflags"] = { text = N_("What the Fractal mapgen makes: caves, dungeons, rivers, floating islands and the rest.") },
	["mgv5_cave_width"] = { text = N_("How wide the cave tunnels are.") },
	["mgv5_cavern_limit"] = { text = N_("Above this height the huge underground halls do not appear.") },
	["mgv5_cavern_taper"] = { text = N_("The height at which those halls start to thin out.") },
	["mgv5_cavern_threshold"] = { text = N_("How often the huge halls turn up. Lower means more of them.") },
	["mgv5_dungeon_ymax"] = { text = N_("Above this height there are no dungeons.") },
	["mgv5_dungeon_ymin"] = { text = N_("Below this height there are no dungeons.") },
	["mgv5_large_cave_depth"] = { text = N_("Below this height the big caves begin.") },
	["mgv5_large_cave_flooded"] = { text = N_("What share of the big caves is flooded with water.") },
	["mgv5_large_cave_num_max"] = { text = N_("The most big caves in one piece of the world.") },
	["mgv5_large_cave_num_min"] = { text = N_("The fewest big caves in one piece of the world.") },
	["mgv5_np_cave1"] = { text = N_("How the cave tunnels wind.") },
	["mgv5_np_cave2"] = { text = N_("The second set of tunnels, crossing the first.") },
	["mgv5_np_cavern"] = { text = N_("Where the huge underground halls are.") },
	["mgv5_np_dungeons"] = { text = N_("Where dungeons turn up.") },
	["mgv5_np_factor"] = { text = N_("How rugged the land is.") },
	["mgv5_np_filler_depth"] = { text = N_("How thick the soil lying on the stone is.") },
	["mgv5_np_ground"] = { text = N_("The shape of the ground itself.") },
	["mgv5_np_height"] = { text = N_("How high the land rises.") },
	["mgv5_small_cave_num_max"] = { text = N_("The most small caves in one piece of the world.") },
	["mgv5_small_cave_num_min"] = { text = N_("The fewest small caves in one piece of the world.") },
	["mgv5_spflags"] = { text = N_("What the V5 mapgen makes: caves, dungeons, rivers, floating islands and the rest.") },
	["mgv6_dungeon_ymax"] = { text = N_("Above this height there are no dungeons.") },
	["mgv6_dungeon_ymin"] = { text = N_("Below this height there are no dungeons.") },
	["mgv6_freq_beach"] = { text = N_("How often beaches turn up.") },
	["mgv6_freq_desert"] = { text = N_("How often deserts turn up.") },
	["mgv6_np_apple_trees"] = { text = N_("Where apple trees grow.") },
	["mgv6_np_beach"] = { text = N_("Where beaches appear.") },
	["mgv6_np_biome"] = { text = N_("How the landscapes are spread over the world.") },
	["mgv6_np_cave"] = { text = N_("Where caves appear.") },
	["mgv6_np_height_select"] = { text = N_("Where the low ground gives way to the high ground.") },
	["mgv6_np_humidity"] = { text = N_("How dampness is spread over the world.") },
	["mgv6_np_mud"] = { text = N_("How thick the layer of mud is.") },
	["mgv6_np_steepness"] = { text = N_("How steep the slopes are.") },
	["mgv6_np_terrain_base"] = { text = N_("The shape of the low ground.") },
	["mgv6_np_terrain_higher"] = { text = N_("The shape of the high ground.") },
	["mgv6_np_trees"] = { text = N_("Where trees grow.") },
	["mgv6_spflags"] = { text = N_("What the V6 mapgen makes: caves, dungeons, rivers, floating islands and the rest.") },
	["mgv7_cave_width"] = { text = N_("How wide the cave tunnels are.") },
	["mgv7_cavern_limit"] = { text = N_("Above this height the huge underground halls do not appear.") },
	["mgv7_cavern_taper"] = { text = N_("The height at which those halls start to thin out.") },
	["mgv7_cavern_threshold"] = { text = N_("How often the huge halls turn up. Lower means more of them.") },
	["mgv7_dungeon_ymax"] = { text = N_("Above this height there are no dungeons.") },
	["mgv7_dungeon_ymin"] = { text = N_("Below this height there are no dungeons.") },
	["mgv7_float_taper_exp"] = { text = N_("How sharply that thinning happens.") },
	["mgv7_floatland_density"] = { text = N_("How much land there is in the floating islands. Less means separate islands, more means a whole layer.") },
	["mgv7_floatland_taper"] = { text = N_("Over what distance the floating islands thin out towards their edges.") },
	["mgv7_floatland_ymax"] = { text = N_("Above this height there are no floating islands.") },
	["mgv7_floatland_ymin"] = { text = N_("Below this height there are no floating islands.") },
	["mgv7_floatland_ywater"] = { text = N_("The height the sea stands at up in the floating islands.") },
	["mgv7_large_cave_depth"] = { text = N_("Below this height the big caves begin.") },
	["mgv7_large_cave_flooded"] = { text = N_("What share of the big caves is flooded with water.") },
	["mgv7_large_cave_num_max"] = { text = N_("The most big caves in one piece of the world.") },
	["mgv7_large_cave_num_min"] = { text = N_("The fewest big caves in one piece of the world.") },
	["mgv7_mount_zero_level"] = { text = N_("The height mountains are measured from.") },
	["mgv7_np_cave1"] = { text = N_("How the cave tunnels wind.") },
	["mgv7_np_cave2"] = { text = N_("The second set of tunnels, crossing the first.") },
	["mgv7_np_cavern"] = { text = N_("Where the huge underground halls are.") },
	["mgv7_np_dungeons"] = { text = N_("Where dungeons turn up.") },
	["mgv7_np_filler_depth"] = { text = N_("How thick the soil lying on the stone is.") },
	["mgv7_np_floatland"] = { text = N_("The shape of the floating islands.") },
	["mgv7_np_height_select"] = { text = N_("Where the low ground gives way to the high ground.") },
	["mgv7_np_mount_height"] = { text = N_("How high the mountains reach.") },
	["mgv7_np_mountain"] = { text = N_("The shape of the mountains.") },
	["mgv7_np_ridge"] = { text = N_("The shape of the river valleys.") },
	["mgv7_np_ridge_uwater"] = { text = N_("Where rivers run.") },
	["mgv7_np_terrain_alt"] = { text = N_("The shape of the second, higher ground.") },
	["mgv7_np_terrain_base"] = { text = N_("The shape of the low ground.") },
	["mgv7_np_terrain_persist"] = { text = N_("How roughness changes from place to place.") },
	["mgv7_small_cave_num_max"] = { text = N_("The most small caves in one piece of the world.") },
	["mgv7_small_cave_num_min"] = { text = N_("The fewest small caves in one piece of the world.") },
	["mgv7_spflags"] = { text = N_("What the V7 mapgen makes: caves, dungeons, rivers, floating islands and the rest.") },
	["mgvalleys_altitude_chill"] = { text = N_("How much colder it gets with height. Higher means snow starts lower down.") },
	["mgvalleys_cave_width"] = { text = N_("How wide the cave tunnels are.") },
	["mgvalleys_cavern_limit"] = { text = N_("Above this height the huge underground halls do not appear.") },
	["mgvalleys_cavern_taper"] = { text = N_("The height at which those halls start to thin out.") },
	["mgvalleys_cavern_threshold"] = { text = N_("How often the huge halls turn up. Lower means more of them.") },
	["mgvalleys_dungeon_ymax"] = { text = N_("Above this height there are no dungeons.") },
	["mgvalleys_dungeon_ymin"] = { text = N_("Below this height there are no dungeons.") },
	["mgvalleys_large_cave_depth"] = { text = N_("Below this height the big caves begin.") },
	["mgvalleys_large_cave_flooded"] = { text = N_("What share of the big caves is flooded with water.") },
	["mgvalleys_large_cave_num_max"] = { text = N_("The most big caves in one piece of the world.") },
	["mgvalleys_large_cave_num_min"] = { text = N_("The fewest big caves in one piece of the world.") },
	["mgvalleys_np_cave1"] = { text = N_("How the cave tunnels wind.") },
	["mgvalleys_np_cave2"] = { text = N_("The second set of tunnels, crossing the first.") },
	["mgvalleys_np_cavern"] = { text = N_("Where the huge underground halls are.") },
	["mgvalleys_np_dungeons"] = { text = N_("Where dungeons turn up.") },
	["mgvalleys_np_filler_depth"] = { text = N_("How thick the soil lying on the stone is.") },
	["mgvalleys_np_inter_valley_fill"] = { text = N_("What fills the space between the valleys.") },
	["mgvalleys_np_inter_valley_slope"] = { text = N_("How steep the slopes between the valleys are.") },
	["mgvalleys_np_rivers"] = { text = N_("Where rivers run.") },
	["mgvalleys_np_terrain_height"] = { text = N_("The height of the land between the valleys.") },
	["mgvalleys_np_valley_depth"] = { text = N_("How deep the valleys are.") },
	["mgvalleys_np_valley_profile"] = { text = N_("How wide the valleys are.") },
	["mgvalleys_river_depth"] = { text = N_("How deep the rivers cut into the land.") },
	["mgvalleys_river_size"] = { text = N_("How wide the rivers are.") },
	["mgvalleys_small_cave_num_max"] = { text = N_("The most small caves in one piece of the world.") },
	["mgvalleys_small_cave_num_min"] = { text = N_("The fewest small caves in one piece of the world.") },
	["mgvalleys_spflags"] = { text = N_("What the Valleys mapgen makes: caves, dungeons, rivers, floating islands and the rest.") },
	["minimap_double_scan_height"] = { text = N_("Let the minimap look further up and down for the surface."), load = "low" },
	["mip_map"] = { text = N_("Keep smaller copies of textures for distant blocks. Distant walls stop flickering, and the game even gets slightly faster."), load = "low" },
	["mono_font_path"] = { text = N_("Font file for monospaced text.") },
	["mono_font_path_bold"] = { text = N_("Font file for bold monospaced text.") },
	["mono_font_path_bold_italic"] = { text = N_("Font file for bold italic monospaced text.") },
	["mono_font_path_italic"] = { text = N_("Font file for italic monospaced text.") },
	["mono_font_size"] = { text = N_("Size of the monospaced text, the kind used in the console.") },
	["mono_font_size_divisible_by"] = { text = N_("Round the monospaced font size to a multiple of this number.") },
	["motd"] = { text = N_("A greeting shown to everyone who joins.") },
	["mouse_sensitivity"] = { text = N_("How far the view turns for the same mouse movement.") },
	["movement_acceleration_air"] = { text = N_("How much you can steer while in the air.") },
	["movement_acceleration_default"] = { text = N_("How quickly you pick up speed on the ground.") },
	["movement_acceleration_fast"] = { text = N_("How quickly you pick up speed when moving fast.") },
	["movement_gravity"] = { text = N_("How strongly gravity pulls you down.") },
	["movement_liquid_fluidity"] = { text = N_("How thick liquids feel to move through.") },
	["movement_liquid_fluidity_smooth"] = { text = N_("How smoothly you slow down when entering a liquid.") },
	["movement_liquid_sink"] = { text = N_("How fast you sink in a liquid.") },
	["movement_speed_climb"] = { text = N_("Speed of climbing ladders and vines.") },
	["movement_speed_crouch"] = { text = N_("Speed while sneaking.") },
	["movement_speed_fast"] = { text = N_("Speed in fast mode.") },
	["movement_speed_jump"] = { text = N_("How high you jump.") },
	["movement_speed_walk"] = { text = N_("Ordinary walking speed.") },
	["mute_sound"] = { text = N_("Turn all sound off completely.") },
	["name"] = { text = N_("The name you play under.") },
	["net_emulate_jitter"] = { text = N_("Pretend the network delay jumps around. For testing.") },
	["net_emulate_latency"] = { text = N_("Pretend the network is slow by this many milliseconds. For testing.") },
	["net_emulate_loss"] = { text = N_("Pretend this share of packets is lost. For testing.") },
	["net_emulate_seed"] = { text = N_("The starting number for that pretend network, so a test can be repeated exactly.") },
	["netsync_diagnostics"] = { text = N_("Collect technical details about what the server sends you. For finding network problems."), load = "low" },
	["netsync_diagnostics_log"] = { text = N_("Where those details are written.") },
	["node_highlighting"] = { text = N_("How the block you are pointing at is marked: an outline around it, a light on it, or nothing."), load = "low" },
	["nodetimer_interval"] = { text = N_("How often blocks with their own timers are checked: furnaces, growing plants."), load = "medium" },
	["num_emerge_threads"] = { text = N_("How many processor cores create the world. More cores load the world faster and leave less for everything else."), load = "medium" },
	["occlusion_culler"] = { text = N_("How the game figures out what is hidden behind walls so it can skip drawing it. Leave it alone unless something looks wrong."), load = "low" },
	["opengl_debug"] = { text = N_("Ask the graphics driver for detailed complaints. For finding rendering bugs."), load = "medium" },
	["pause_on_lost_focus"] = { text = N_("Pause the game when you switch to another window. Handy if you often alt-tab and do not want to be attacked while away.") },
	["performance_tradeoffs"] = { text = N_("Give up a bit of beauty in several places at once for the sake of speed. Worth turning on if the game stutters."), load = "low" },
	["player_transfer_distance"] = { text = N_("How far away other players are still visible."), load = "low" },
	["port"] = { text = N_("The port your server listens on.") },
	["post_processing_texture_bits"] = { text = N_("How precisely the finishing touches are stored. More precision means smoother light and more video memory."), load = "medium" },
	["profiler_print_interval"] = { text = N_("How often the performance report is printed to the log. Zero turns it off.") },
	["prometheus_listener_address"] = { text = N_("Address for the server statistics service. For those who watch their server through graphs.") },
	["protocol_version_min"] = { text = N_("The oldest client version the server still accepts.") },
	["random_input"] = { text = N_("Play the game with random input. For testing.") },
	["random_mod_load_order"] = { text = N_("Load mods in a random order, to catch mods that quietly depend on each other.") },
	["recent_chat_messages"] = { text = N_("How many chat lines stay on the screen.") },
	["remote_media"] = { text = N_("An address clients can download textures and sounds from, faster than through the server itself.") },
	["repeat_dig_time"] = { text = N_("How often you hit the block again while holding the dig button.") },
	["repeat_joystick_button_time"] = { text = N_("How often a held gamepad button repeats.") },
	["repeat_place_time"] = { text = N_("How often blocks are placed while you hold the button down.") },
	["safe_dig_and_place"] = { text = N_("Require releasing the button between actions, so you do not dig or build by accident.") },
	["screen_h"] = { text = N_("How tall the game window is when it is not fullscreen. Like the width: a bigger window means a bit fewer frames."), load = "medium" },
	["screen_w"] = { text = N_("How wide the game window is when it is not fullscreen. A bigger window looks better but the game has to draw more, so the frame rate drops a little."), load = "medium" },
	["screenshot_after"] = { text = N_("Take a screenshot automatically this many seconds after entering the world. Zero turns it off; the test stands use it.") },
	["screenshot_format"] = { text = N_("File type for screenshots. PNG keeps the picture exactly; JPG files are smaller but lose a little detail.") },
	["screenshot_path"] = { text = N_("The folder your screenshots are saved to.") },
	["screenshot_quality"] = { text = N_("How good JPG screenshots look. Higher means a better picture and a bigger file. Does nothing for PNG.") },
	["selectionbox_color"] = { text = N_("Colour of the box around the block you are pointing at.") },
	["selectionbox_width"] = { text = N_("How thick that box is.") },
	["server_address"] = { text = N_("The address players connect to.") },
	["server_announce"] = { text = N_("Announce the server publicly, so anyone can find it in the list.") },
	["server_announce_send_players"] = { text = N_("Also tell the list who is playing right now.") },
	["server_description"] = { text = N_("A short line about your server for the same list.") },
	["server_map_save_interval"] = { text = N_("How often the world is written to disk, in seconds. Rarer saving is faster and loses more when the power goes out."), load = "medium" },
	["server_name"] = { text = N_("The name your server shows in the server list.") },
	["server_side_occlusion_culling"] = { text = N_("Let the server skip sending pieces of the world hidden behind others. Saves traffic."), load = "low" },
	["server_unload_unused_data_timeout"] = { text = N_("How long the server keeps a piece of the world nobody is near.") },
	["server_url"] = { text = N_("A website of your server, if there is one.") },
	["serverlist_url"] = { text = N_("Where the list of public servers comes from.") },
	["shader_path"] = { text = N_("Folder the drawing programs are loaded from. Leave empty unless you are writing your own.") },
	["shadow_filters"] = { text = N_("How soft the shadow edges are. Softer edges look nicer and cost frames."), load = "medium" },
	["shadow_map_color"] = { text = N_("Let coloured glass tint its own shadow. Beautiful, and heavy: the shadows have to be drawn a second time."), load = "high" },
	["shadow_map_max_distance"] = { text = N_("How far away shadows are still drawn. Further means the shadows get blurrier rather than slower."), load = "low" },
	["shadow_map_texture_32bit"] = { text = N_("Store shadows more precisely. Removes ugly stripes in them, but takes twice the video memory."), load = "medium" },
	["shadow_map_texture_size"] = { text = N_("How sharp the shadows are. Every step up costs a lot: doubling the number roughly quadruples the work."), load = "high" },
	["shadow_poisson_filter"] = { text = N_("Blur shadow edges in a scattered pattern, which looks softer than a plain blur."), load = "medium" },
	["shadow_sky_body_orbit_tilt"] = { text = N_("How slanted the sun's path across the sky is. Changes where the shadows fall.") },
	["shadow_soft_radius"] = { text = N_("How wide the blurred edge of a shadow is."), load = "medium" },
	["shadow_strength_gamma"] = { text = N_("How dark the shadows are. Costs nothing once shadows are on.") },
	["shadow_update_frames"] = { text = N_("Over how many frames the distant shadows are refreshed. More frames means cheaper shadows that lag a little behind."), load = "medium" },
	["show_block_bounds_radius_near"] = { text = N_("How far around you the block boundary grid is drawn when it is turned on."), load = "medium" },
	["show_debug"] = { text = N_("Show the technical information panel. Handy when something goes wrong, in the way the rest of the time."), load = "low" },
	["show_entity_selectionbox"] = { text = N_("Also draw a box around creatures and items you point at, not only around blocks."), load = "low" },
	["show_nametag_backgrounds"] = { text = N_("Draw a dark plate behind player names so they stay readable against the sky.") },
	["smooth_lighting"] = { text = N_("Make light fade softly across corners instead of jumping from block to block. Costs a little when the world loads, nothing while you walk around."), load = "medium" },
	["smooth_scrolling"] = { text = N_("Let lists glide when you scroll them instead of jumping line by line.") },
	["soft_clouds"] = { text = N_("Make the edges of the clouds softer, less like cut paper."), load = "low" },
	["sound_extensions_blacklist"] = { text = N_("Sound file types the game will not load.") },
	["sound_volume"] = { text = N_("How loud the game is overall.") },
	["sound_volume_unfocused"] = { text = N_("How loud the game stays when you switch to another window.") },
	["sqlite_synchronous"] = { text = N_("How carefully the world is written to disk. Safer means slower saving."), load = "medium" },
	["static_spawnpoint"] = { text = N_("A fixed place everyone appears at. Empty means the server picks one.") },
	["strict_protocol_version_checking"] = { text = N_("Only let in clients of exactly the same version.") },
	["strip_color_codes"] = { text = N_("Remove colouring from chat messages and show them in plain text.") },
	["texture_min_size"] = { text = N_("The smallest size textures are enlarged to. Raise it if pixel art looks muddy with smoothing on."), load = "medium" },
	["time_speed"] = { text = N_("How much faster the in-game day runs compared to a real one.") },
	["toggle_aux1_key"] = { text = N_("The same switch behaviour for the special key.") },
	["toggle_sneak_key"] = { text = N_("Make the sneak key work as a switch: press once to sneak, press again to stand up.") },
	["tone_mapping"] = { text = N_("Handle very bright and very dark places the way a camera does, instead of turning them into flat white and flat black."), load = "low" },
	["tooltip_append_itemname"] = { text = N_("Also show the technical name of an item in its hint. Useful when writing commands or mods.") },
	["tooltip_show_delay"] = { text = N_("How long you have to hold the pointer still before a hint appears, in thousandths of a second.") },
	["touch_controls"] = { text = N_("On-screen controls for playing with fingers.") },
	["touch_gui"] = { text = N_("Lay the interface out for a touchscreen: bigger buttons, on-screen controls.") },
	["touch_interaction_style"] = { text = N_("How a tap is understood on a touchscreen: what digs, what places, what opens.") },
	["touch_long_tap_delay"] = { text = N_("How long a finger must be held down for a long press.") },
	["touch_punch_gesture"] = { text = N_("Which gesture counts as a hit on a touchscreen.") },
	["touchscreen_sensitivity"] = { text = N_("How far the view turns for the same finger movement.") },
	["touchscreen_threshold"] = { text = N_("How far a finger has to move before it counts as a swipe rather than a tap.") },
	["translucent_liquids"] = { text = N_("Make water see-through, so you can look at the bottom while swimming."), load = "low" },
	["transparency_sorting_distance"] = { text = N_("How far away see-through things are sorted so they overlap correctly. Further looks right and costs a little."), load = "medium" },
	["transparency_sorting_group_by_buffers"] = { text = N_("Sort see-through things in groups instead of one by one. Faster, occasionally slightly wrong.") },
	["trilinear_filter"] = { text = N_("Smooth the moment when a distant block switches to a simpler texture, so you do not see the seam."), load = "low" },
	["undersampling"] = { text = N_("Draw the world coarser than the screen, keeping menus sharp. The picture becomes blocky, but the game speeds up a lot — a good last resort on a weak computer."), load = "high" },
	["unlimited_player_transfer_distance"] = { text = N_("Let players see each other at any distance.") },
	["video_driver"] = { text = N_("Which graphics system the game talks to. Change it only if the picture is broken or the game will not start.") },
	["view_bobbing_amount"] = { text = N_("How much the view rocks while you walk. Set it to zero if walking makes you dizzy.") },
	["viewing_range"] = { text = N_("How far you can see. This is the setting that changes speed the most: every step further means much more world to load and draw."), load = "high" },
	["virtual_joystick_triggers_aux1"] = { text = N_("Let pushing the on-screen stick to the edge work as the special key.") },
	["volumetric_clouds_density"] = { text = N_("How thick the clouds are.") },
	["volumetric_clouds_distance"] = { text = N_("How far into the distance the clouds are drawn. The heaviest of the cloud settings by a wide margin."), load = "high" },
	["volumetric_clouds_height"] = { text = N_("How high the clouds float.") },
	["volumetric_clouds_pixel"] = { text = N_("Draw the clouds coarser than the screen. The sky looks a little rougher, and the game gets noticeably lighter — the first thing to try if clouds are too heavy."), load = "high" },
	["volumetric_clouds_roundness"] = { text = N_("How round the clouds look.") },
	["volumetric_clouds_size"] = { text = N_("How big the cloud shapes are.") },
	["volumetric_clouds_speed"] = { text = N_("How fast the clouds drift.") },
	["volumetric_clouds_thickness"] = { text = N_("How deep the cloud layer is. Thicker clouds cost more."), load = "medium" },
	["vsync"] = { text = N_("Match the game to your monitor so the picture never tears in the middle. In return the game feels a touch less responsive. Takes effect after a restart."), load = "low" },
	["wait_for_server"] = { text = N_("Wait for the local server to be ready before entering a single player game.") },
	["wait_for_server_timeout"] = { text = N_("How long to wait for it before giving up.") },
	["water_level"] = { text = N_("The height the sea stands at.") },
	["water_wave_height"] = { text = N_("How high the waves rise.") },
	["water_wave_length"] = { text = N_("How far apart the waves are.") },
	["water_wave_speed"] = { text = N_("How fast the waves run.") },
	["window_maximized"] = { text = N_("Open the window already stretched to the whole screen."), load = "low" },
	["world_aligned_mode"] = { text = N_("Line textures up with the world instead of with each block, so large walls look like one surface."), load = "low" },
	["world_start_time"] = { text = N_("What time of day a new world begins at.") },
}
