-- Axis
-- SPDX-License-Identifier: LGPL-2.1-or-later

-- Что делает настройка и во что она обходится.
--
-- Родные описания движка писались как подсказки для тех, кто и так знает
-- устройство: строка-другая, без единого слова о цене. В меню же читает игрок,
-- которому нужно решить, чем пожертвовать ради частоты кадров, — поэтому здесь
-- у каждой настройки сказано и что она меняет, и сколько это стоит.
--
-- Поле load — требовательность: high, medium, low. Её меню дописывает
-- отдельной строкой и красит, чтобы уровень был виден, не читая текста.
-- Настройке, которая ничего не стоит, поле не нужно.

local S = fgettext_ne

return {
	["3d_mode"] = { text = S("Stereo picture for 3D glasses or a split screen. Anything except «none» draws the world twice and roughly halves the frame rate."), load = "high" },
	["3d_paralax_strength"] = { text = S("How far apart the two pictures are in 3D mode. Changes how deep the picture feels.") },
	["always_fly_fast"] = { text = S("Always fly at full speed, without holding the fast key.") },
	["ambient_occlusion_gamma"] = { text = S("How dark the corners between blocks look. Higher means softer shading in the corners.") },
	["anisotropic_filter"] = { text = S("Keep textures sharp on surfaces you see edge-on, like a floor stretching away. Cheap and noticeable."), load = "medium" },
	["antialiasing"] = { text = S("How the jagged staircase edges are smoothed. FSAA is the cleanest and the heaviest, FXAA is almost free but slightly blurry."), load = "medium" },
	["arm_inertia"] = { text = S("Let the item in your hand swing a little behind the camera when you turn. Just for looks.") },
	["autojump"] = { text = S("Step up single blocks automatically, without pressing jump.") },
	["autosave_screensize"] = { text = S("Remember the window size, so next time the game opens exactly as you left it.") },
	["aux1_descends"] = { text = S("Make the special key move you down while flying or climbing, instead of doing what it usually does.") },
	["bilinear_filter"] = { text = S("Smooth textures when you stand close to them. Some like it, some prefer sharp pixels."), load = "low" },
	["bind_address"] = { text = S("Which network address the server listens on. Empty means all of them.") },
	["camera_smoothing"] = { text = S("How softly the camera follows your mouse. Higher makes the view smoother and a little slower to respond.") },
	["chat_font_size"] = { text = S("Size of the chat text. Zero means the usual size.") },
	["chat_log_level"] = { text = S("Which messages also appear in the in-game chat.") },
	["chat_message_limit_per_10sec"] = { text = S("How many messages one player may send in ten seconds before being told to slow down.") },
	["chat_message_limit_trigger_kick"] = { text = S("After how many messages over the limit a player is kicked off the server.") },
	["chat_message_max_size"] = { text = S("The longest message a player may send. Longer ones are cut.") },
	["chat_weblink_color"] = { text = S("Colour of clickable links in chat.") },
	["cinematic_camera_smoothing"] = { text = S("The same softness, but for cinematic mode, where the camera is meant to glide.") },
	["clickable_chat_weblinks"] = { text = S("Make links in chat clickable.") },
	["client_mapblock_limit"] = { text = S("How many pieces of the world are kept in memory at once. Fewer means less memory and more reloading."), load = "medium" },
	["client_unload_unused_data_timeout"] = { text = S("How long the game keeps parts of the world you have left before forgetting them, in seconds.") },
	["connected_glass"] = { text = S("Join glass blocks placed next to each other into one clean pane, without lines between them."), load = "low" },
	["console_alpha"] = { text = S("How solid the chat console background is.") },
	["console_color"] = { text = S("Background colour of the chat console.") },
	["console_height"] = { text = S("How much of the screen the chat console takes when opened.") },
	["contentdb_enable_updates_indicator"] = { text = S("Show a mark when an installed add-on has a newer version.") },
	["contentdb_flag_blacklist"] = { text = S("Hide content marked with these flags, such as adult or non-free.") },
	["contentdb_max_concurrent_downloads"] = { text = S("How many add-ons may download at the same time.") },
	["contentdb_url"] = { text = S("Where the game looks for downloadable content.") },
	["crosshair_alpha"] = { text = S("How visible the crosshair is. Zero hides it completely.") },
	["crosshair_color"] = { text = S("Colour of the crosshair in the middle of the screen.") },
	["csm_restriction_flags"] = { text = S("What client-side mods are forbidden to do on this server.") },
	["csm_restriction_noderange"] = { text = S("How far around the player client-side mods may look at the world.") },
	["curl_file_download_timeout"] = { text = S("The same limit for large files.") },
	["curl_parallel_limit"] = { text = S("How many downloads may run at the same time.") },
	["curl_timeout"] = { text = S("How long a download may take before it is called failed.") },
	["debanding"] = { text = S("Remove the ugly stripes that show up on smooth gradients, like the evening sky."), load = "low" },
	["debug_log_level"] = { text = S("How much detail goes into the log file. More detail helps find problems and makes the file grow fast."), load = "low" },
	["debug_log_size_max"] = { text = S("How big the log may grow before it starts over, in kilobytes.") },
	["deprecated_lua_api_handling"] = { text = S("What to do when a mod uses an outdated feature: keep quiet, warn, or stop.") },
	["directional_colored_fog"] = { text = S("Colour the haze like the sky in the direction you are looking. Sunsets look much better with it."), load = "low" },
	["display_density_factor"] = { text = S("How dense your screen is. Affects how big everything looks; usually best left alone.") },
	["display_gamma"] = { text = S("Overall brightness of the picture. Raise it if dark places are too dark to see anything.") },
	["doubletap_jump"] = { text = S("Turn flying on and off by tapping jump twice.") },
	["enable_3d_clouds"] = { text = S("Make clouds solid instead of a flat sheet. They look much better from below and while flying."), load = "low" },
	["enable_all_mods"] = { text = S("Turn on every mod of the game, ignoring what the world has enabled.") },
	["enable_auto_exposure"] = { text = S("Let your eyes adjust: step out of a cave and the light slowly settles down, just like in life."), load = "low" },
	["enable_bloom"] = { text = S("Let bright things glow softly around themselves, like the sun through leaves."), load = "medium" },
	["enable_build_where_you_stand"] = { text = S("Allow placing blocks in the space you are standing in.") },
	["enable_client_modding"] = { text = S("Allow mods that run on your own computer."), load = "low" },
	["enable_console"] = { text = S("Show a separate console window next to the game. Windows only.") },
	["enable_dynamic_shadows"] = { text = S("Let the sun and moon cast real shadows. This is the most beautiful and the heaviest effect in the game: expect to lose a noticeable part of your frames."), load = "high" },
	["enable_esc_dialog"] = { text = S("Ask before leaving the game when you press escape.") },
	["enable_fog"] = { text = S("Fade the far edge of the world into a haze, instead of showing where the world simply stops."), load = "low" },
	["enable_hotbar_mouse_wheel"] = { text = S("Switch the item in your hand with the mouse wheel.") },
	["enable_ipv6"] = { text = S("Allow IPv6 connections at all.") },
	["enable_local_map_saving"] = { text = S("Keep the parts of the world you have seen on a server, so they load from your disk next time."), load = "low" },
	["enable_mod_channels"] = { text = S("Let mods talk to each other over their own channels.") },
	["enable_post_processing"] = { text = S("The master switch for the finishing touches: glow, tone, exposure. With it off none of them cost anything."), load = "medium" },
	["enable_raytraced_culling"] = { text = S("Check more carefully what is hidden behind walls. Fewer invisible blocks get drawn, but the checking itself takes some work."), load = "medium" },
	["enable_remote_media_server"] = { text = S("Let clients fetch textures and sounds from the address given above.") },
	["enable_split_login_register"] = { text = S("Ask separately whether you are logging in or registering a new account.") },
	["enable_sscsm"] = { text = S("Allow the server to send mods that run on your computer.") },
	["enable_translucent_foliage"] = { text = S("Let sunlight shine through leaves so they glow when the sun is behind them."), load = "low" },
	["enable_volumetric_clouds"] = { text = S("Replace flat clouds with real ones you can fly through. Very beautiful and very heavy."), load = "high" },
	["enable_volumetric_lighting"] = { text = S("Draw sunbeams in the air. Best seen when you look towards the sun."), load = "medium" },
	["enable_water_reflections"] = { text = S("Reflect the sky and the shore in the water."), load = "medium" },
	["enable_waving_leaves"] = { text = S("Let leaves sway in the wind. Pretty, and a little heavier in a thick forest."), load = "medium" },
	["enable_waving_plants"] = { text = S("Let grass and flowers sway in the wind."), load = "medium" },
	["enable_waving_water"] = { text = S("Let the water surface move in waves instead of lying flat like glass."), load = "medium" },
	["exposure_compensation"] = { text = S("Make the whole picture brighter or darker.") },
	["fallback_font_path"] = { text = S("The font used for letters the main font does not have — Chinese or Japanese, for example.") },
	["fixed_virtual_joystick"] = { text = S("Keep the on-screen stick in one place instead of putting it where you touch.") },
	["fog_start"] = { text = S("How close the haze begins. Closer haze hides the distance, but the game still draws what is behind it.") },
	["font_bold"] = { text = S("Use the bold face for all text.") },
	["font_italic"] = { text = S("Use the italic face for all text.") },
	["font_path"] = { text = S("Which font file the game uses for ordinary text.") },
	["font_path_bold"] = { text = S("Font file for bold text.") },
	["font_path_bold_italic"] = { text = S("Font file for bold italic text.") },
	["font_path_italic"] = { text = S("Font file for italic text.") },
	["font_shadow"] = { text = S("How far the shadow under the letters is offset. Makes text readable on a light background.") },
	["font_shadow_alpha"] = { text = S("How dark that shadow is.") },
	["font_size"] = { text = S("Size of the main text in the game.") },
	["font_size_divisible_by"] = { text = S("Round the font size to a multiple of this number. For pixel fonts, so they stay crisp.") },
	["formspec_fullscreen_bg_color"] = { text = S("Colour of that dimming.") },
	["formspec_fullscreen_bg_opacity"] = { text = S("How much the game behind a fullscreen window is dimmed.") },
	["fov"] = { text = S("How wide a view you have. A wider view shows more around you, but the game has to draw more of the world at once."), load = "medium" },
	["fps_max"] = { text = S("The highest number of frames per second the game will draw. Extra frames you cannot see anyway only heat up the computer, so a limit near your monitor's refresh rate is a good idea."), load = "low" },
	["fps_max_unfocused"] = { text = S("Frame limit while the game window is in the background. Keep it low so the game does not eat the computer while you are doing something else."), load = "low" },
	["fsaa"] = { text = S("How thoroughly the edges are smoothed. Every step up is much heavier for the graphics card: four times means about four times the work on the world."), load = "high" },
	["full_block_send_enable_min_time_from_building"] = { text = S("How long after building the server waits before sending whole pieces of the world again.") },
	["fullscreen"] = { text = S("Play on the whole screen instead of in a window. Usually a bit smoother than a window of the same size."), load = "low" },
	["fxaa"] = { text = S("Smooth the edges after the frame is drawn. Costs almost nothing, but small details get a little soft."), load = "low" },
	["gui_scaling"] = { text = S("How big menus and windows are. Raise it if the text is too small on a big screen."), load = "low" },
	["gui_scaling_filter"] = { text = S("Smooth interface pictures when they are stretched. Turn it off if you like sharp pixels."), load = "low" },
	["hud_hotbar_max_width"] = { text = S("How wide the hotbar is allowed to be, as a share of the screen.") },
	["hud_scaling"] = { text = S("How big the on-screen indicators are: health, hotbar, and the rest.") },
	["hurt_flash_enabled"] = { text = S("Flash the screen red when you get hurt, so you notice it even in a fight.") },
	["ignore_world_load_errors"] = { text = S("Enter the world even if part of it failed to load. Dangerous: the damage may spread.") },
	["inventory_items_animations"] = { text = S("Let animated blocks keep moving inside the inventory as well."), load = "low" },
	["invert_hotbar_mouse_wheel"] = { text = S("Reverse the direction the wheel switches items in.") },
	["invert_mouse"] = { text = S("Turn the vertical mouse movement upside down.") },
	["ipv6_server"] = { text = S("Let the server accept connections over IPv6 as well.") },
	["joystick_frustum_sensitivity"] = { text = S("How fast the view turns with the gamepad stick.") },
	["joystick_inner_deadzone"] = { text = S("How far the stick must move before the game notices. Raise it if the view drifts on its own.") },
	["joystick_outer_deadzone"] = { text = S("How close to the edge the stick counts as fully pushed.") },
	["keyboard_camera_speed"] = { text = S("How fast the view turns when you look around with the keyboard.") },
	["keymap_quicktune_dec"] = { text = S("Decrease the value in that tool.") },
	["keymap_quicktune_inc"] = { text = S("Increase the value in that tool.") },
	["keymap_quicktune_next"] = { text = S("Next value in that tool.") },
	["keymap_quicktune_prev"] = { text = S("Previous value in the developer's quick tuning tool.") },
	["keymap_toggle_update_camera"] = { text = S("Freeze the camera where it is, to look at how the world is drawn from outside.") },
	["leaves_style"] = { text = S("How leaves are drawn. «Fancy» looks like real foliage, «simple» is lighter, and «opaque» turns leaves into solid blocks — the fastest by far. In a forest the difference is very noticeable."), load = "medium" },
	["lighting_alpha"] = { text = S("How dark the darkest places are.") },
	["lighting_beta"] = { text = S("How bright the brightest places are.") },
	["lighting_boost"] = { text = S("Extra light added around a chosen brightness.") },
	["lighting_boost_center"] = { text = S("Which brightness gets that extra light.") },
	["lighting_boost_spread"] = { text = S("How wide a range of brightness the addition covers.") },
	["main_menu_script"] = { text = S("A script that replaces the main menu. For those building their own.") },
	["map_compression_level_disk"] = { text = S("How hard the world is squeezed when saved to disk."), load = "medium" },
	["map_compression_level_net"] = { text = S("How hard the world is squeezed before being sent. Harder saves traffic and costs processor time."), load = "medium" },
	["max_clearobjects_extra_loaded_blocks"] = { text = S("How many extra pieces of the world may be loaded at once while cleaning up objects.") },
	["max_out_chat_queue_size"] = { text = S("How many chat messages may wait in line before the oldest are dropped.") },
	["max_packets_per_iteration"] = { text = S("How many network packets the server handles in one go.") },
	["max_simultaneous_block_sends_per_client"] = { text = S("How many pieces of the world the server sends one player at a time.") },
	["menu_clouds"] = { text = S("Show moving clouds behind the main menu."), load = "low" },
	["menu_theme"] = { text = S("Which look the main menu uses.") },
	["mip_map"] = { text = S("Keep smaller copies of textures for distant blocks. Distant walls stop flickering, and the game even gets slightly faster."), load = "low" },
	["mono_font_path"] = { text = S("Font file for monospaced text.") },
	["mono_font_path_bold"] = { text = S("Font file for bold monospaced text.") },
	["mono_font_path_bold_italic"] = { text = S("Font file for bold italic monospaced text.") },
	["mono_font_path_italic"] = { text = S("Font file for italic monospaced text.") },
	["mono_font_size"] = { text = S("Size of the monospaced text, the kind used in the console.") },
	["mono_font_size_divisible_by"] = { text = S("Round the monospaced font size to a multiple of this number.") },
	["mouse_sensitivity"] = { text = S("How far the view turns for the same mouse movement.") },
	["movement_acceleration_air"] = { text = S("How much you can steer while in the air.") },
	["movement_acceleration_default"] = { text = S("How quickly you pick up speed on the ground.") },
	["movement_acceleration_fast"] = { text = S("How quickly you pick up speed when moving fast.") },
	["movement_gravity"] = { text = S("How strongly gravity pulls you down.") },
	["movement_liquid_fluidity"] = { text = S("How thick liquids feel to move through.") },
	["movement_liquid_fluidity_smooth"] = { text = S("How smoothly you slow down when entering a liquid.") },
	["movement_liquid_sink"] = { text = S("How fast you sink in a liquid.") },
	["movement_speed_climb"] = { text = S("Speed of climbing ladders and vines.") },
	["movement_speed_crouch"] = { text = S("Speed while sneaking.") },
	["movement_speed_fast"] = { text = S("Speed in fast mode.") },
	["movement_speed_jump"] = { text = S("How high you jump.") },
	["movement_speed_walk"] = { text = S("Ordinary walking speed.") },
	["mute_sound"] = { text = S("Turn all sound off completely.") },
	["net_emulate_jitter"] = { text = S("Pretend the network delay jumps around. For testing.") },
	["net_emulate_latency"] = { text = S("Pretend the network is slow by this many milliseconds. For testing.") },
	["net_emulate_loss"] = { text = S("Pretend this share of packets is lost. For testing.") },
	["net_emulate_seed"] = { text = S("The starting number for that pretend network, so a test can be repeated exactly.") },
	["netsync_diagnostics"] = { text = S("Collect technical details about what the server sends you. For finding network problems."), load = "low" },
	["netsync_diagnostics_log"] = { text = S("Where those details are written.") },
	["node_highlighting"] = { text = S("How the block you are pointing at is marked: an outline around it, a light on it, or nothing."), load = "low" },
	["occlusion_culler"] = { text = S("How the game figures out what is hidden behind walls so it can skip drawing it. Leave it alone unless something looks wrong."), load = "low" },
	["pause_on_lost_focus"] = { text = S("Pause the game when you switch to another window. Handy if you often alt-tab and do not want to be attacked while away.") },
	["performance_tradeoffs"] = { text = S("Give up a bit of beauty in several places at once for the sake of speed. Worth turning on if the game stutters."), load = "low" },
	["port"] = { text = S("The port your server listens on.") },
	["profiler_print_interval"] = { text = S("How often the performance report is printed to the log. Zero turns it off.") },
	["prometheus_listener_address"] = { text = S("Address for the server statistics service. For those who watch their server through graphs.") },
	["protocol_version_min"] = { text = S("The oldest client version the server still accepts.") },
	["random_input"] = { text = S("Play the game with random input. For testing.") },
	["random_mod_load_order"] = { text = S("Load mods in a random order, to catch mods that quietly depend on each other.") },
	["recent_chat_messages"] = { text = S("How many chat lines stay on the screen.") },
	["remote_media"] = { text = S("An address clients can download textures and sounds from, faster than through the server itself.") },
	["repeat_dig_time"] = { text = S("How often you hit the block again while holding the dig button.") },
	["repeat_joystick_button_time"] = { text = S("How often a held gamepad button repeats.") },
	["repeat_place_time"] = { text = S("How often blocks are placed while you hold the button down.") },
	["safe_dig_and_place"] = { text = S("Require releasing the button between actions, so you do not dig or build by accident.") },
	["screen_h"] = { text = S("How tall the game window is when it is not fullscreen. Like the width: a bigger window means a bit fewer frames."), load = "medium" },
	["screen_w"] = { text = S("How wide the game window is when it is not fullscreen. A bigger window looks better but the game has to draw more, so the frame rate drops a little."), load = "medium" },
	["screenshot_after"] = { text = S("Take a screenshot automatically this many seconds after entering the world. Zero turns it off; the test stands use it.") },
	["screenshot_format"] = { text = S("File type for screenshots. PNG keeps the picture exactly; JPG files are smaller but lose a little detail.") },
	["screenshot_path"] = { text = S("The folder your screenshots are saved to.") },
	["screenshot_quality"] = { text = S("How good JPG screenshots look. Higher means a better picture and a bigger file. Does nothing for PNG.") },
	["selectionbox_color"] = { text = S("Colour of the box around the block you are pointing at.") },
	["selectionbox_width"] = { text = S("How thick that box is.") },
	["serverlist_file"] = { text = S("The file your favourite servers are stored in.") },
	["serverlist_url"] = { text = S("Where the list of public servers comes from.") },
	["shadow_filters"] = { text = S("How soft the shadow edges are. Softer edges look nicer and cost frames."), load = "medium" },
	["shadow_map_color"] = { text = S("Let coloured glass tint its own shadow. Beautiful, and heavy: the shadows have to be drawn a second time."), load = "high" },
	["shadow_map_max_distance"] = { text = S("How far away shadows are still drawn. Further means the shadows get blurrier rather than slower."), load = "low" },
	["shadow_map_texture_32bit"] = { text = S("Store shadows more precisely. Removes ugly stripes in them, but takes twice the video memory."), load = "medium" },
	["shadow_map_texture_size"] = { text = S("How sharp the shadows are. Every step up costs a lot: doubling the number roughly quadruples the work."), load = "high" },
	["shadow_sky_body_orbit_tilt"] = { text = S("How slanted the sun's path across the sky is. Changes where the shadows fall.") },
	["shadow_soft_radius"] = { text = S("How wide the blurred edge of a shadow is."), load = "medium" },
	["shadow_strength_gamma"] = { text = S("How dark the shadows are. Costs nothing once shadows are on.") },
	["show_block_bounds_radius_near"] = { text = S("How far around you the block boundary grid is drawn when it is turned on."), load = "medium" },
	["show_debug"] = { text = S("Show the technical information panel. Handy when something goes wrong, in the way the rest of the time."), load = "low" },
	["show_entity_selectionbox"] = { text = S("Also draw a box around creatures and items you point at, not only around blocks."), load = "low" },
	["show_nametag_backgrounds"] = { text = S("Draw a dark plate behind player names so they stay readable against the sky.") },
	["smooth_lighting"] = { text = S("Make light fade softly across corners instead of jumping from block to block. Costs a little when the world loads, nothing while you walk around."), load = "medium" },
	["smooth_scrolling"] = { text = S("Let lists glide when you scroll them instead of jumping line by line.") },
	["soft_clouds"] = { text = S("Make the edges of the clouds softer, less like cut paper."), load = "low" },
	["sound_extensions_blacklist"] = { text = S("Sound file types the game will not load.") },
	["sound_volume"] = { text = S("How loud the game is overall.") },
	["sound_volume_unfocused"] = { text = S("How loud the game stays when you switch to another window.") },
	["sqlite_synchronous"] = { text = S("How carefully the world is written to disk. Safer means slower saving."), load = "medium" },
	["strict_protocol_version_checking"] = { text = S("Only let in clients of exactly the same version.") },
	["strip_color_codes"] = { text = S("Remove colouring from chat messages and show them in plain text.") },
	["toggle_aux1_key"] = { text = S("The same switch behaviour for the special key.") },
	["toggle_sneak_key"] = { text = S("Make the sneak key work as a switch: press once to sneak, press again to stand up.") },
	["tone_mapping"] = { text = S("Handle very bright and very dark places the way a camera does, instead of turning them into flat white and flat black."), load = "low" },
	["tooltip_append_itemname"] = { text = S("Also show the technical name of an item in its hint. Useful when writing commands or mods.") },
	["tooltip_show_delay"] = { text = S("How long you have to hold the pointer still before a hint appears, in thousandths of a second.") },
	["touch_controls"] = { text = S("On-screen controls for playing with fingers.") },
	["touch_gui"] = { text = S("Lay the interface out for a touchscreen: bigger buttons, on-screen controls.") },
	["touch_interaction_style"] = { text = S("How a tap is understood on a touchscreen: what digs, what places, what opens.") },
	["touch_long_tap_delay"] = { text = S("How long a finger must be held down for a long press.") },
	["touch_punch_gesture"] = { text = S("Which gesture counts as a hit on a touchscreen.") },
	["touchscreen_sensitivity"] = { text = S("How far the view turns for the same finger movement.") },
	["touchscreen_threshold"] = { text = S("How far a finger has to move before it counts as a swipe rather than a tap.") },
	["translucent_liquids"] = { text = S("Make water see-through, so you can look at the bottom while swimming."), load = "low" },
	["trilinear_filter"] = { text = S("Smooth the moment when a distant block switches to a simpler texture, so you do not see the seam."), load = "low" },
	["undersampling"] = { text = S("Draw the world coarser than the screen, keeping menus sharp. The picture becomes blocky, but the game speeds up a lot — a good last resort on a weak computer."), load = "high" },
	["view_bobbing_amount"] = { text = S("How much the view rocks while you walk. Set it to zero if walking makes you dizzy.") },
	["viewing_range"] = { text = S("How far you can see. This is the setting that changes speed the most: every step further means much more world to load and draw."), load = "high" },
	["virtual_joystick_triggers_aux1"] = { text = S("Let pushing the on-screen stick to the edge work as the special key.") },
	["volumetric_clouds_density"] = { text = S("How thick the clouds are.") },
	["volumetric_clouds_distance"] = { text = S("How far into the distance the clouds are drawn. The heaviest of the cloud settings by a wide margin."), load = "high" },
	["volumetric_clouds_height"] = { text = S("How high the clouds float.") },
	["volumetric_clouds_pixel"] = { text = S("Draw the clouds coarser than the screen. The sky looks a little rougher, and the game gets noticeably lighter — the first thing to try if clouds are too heavy."), load = "high" },
	["volumetric_clouds_roundness"] = { text = S("How round the clouds look.") },
	["volumetric_clouds_size"] = { text = S("How big the cloud shapes are.") },
	["volumetric_clouds_speed"] = { text = S("How fast the clouds drift.") },
	["volumetric_clouds_thickness"] = { text = S("How deep the cloud layer is. Thicker clouds cost more."), load = "medium" },
	["vsync"] = { text = S("Match the game to your monitor so the picture never tears in the middle. In return the game feels a touch less responsive. Takes effect after a restart."), load = "low" },
	["wait_for_server"] = { text = S("Wait for the local server to be ready before entering a single player game.") },
	["wait_for_server_timeout"] = { text = S("How long to wait for it before giving up.") },
	["water_wave_height"] = { text = S("How high the waves rise.") },
	["water_wave_length"] = { text = S("How far apart the waves are.") },
	["water_wave_speed"] = { text = S("How fast the waves run.") },
	["window_maximized"] = { text = S("Open the window already stretched to the whole screen."), load = "low" },
}
