-- Axis
-- SPDX-License-Identifier: LGPL-2.1-or-later

-- Что делает настройка и во что она обходится.
--
-- Родные описания движка писались как подсказки для тех, кто и так знает
-- устройство: строка-другая, без единого слова о цене. В меню же читает игрок,
-- которому нужно решить, чем пожертвовать ради частоты кадров, — поэтому здесь
-- у каждой настройки сказано и что она меняет, и сколько это стоит, если стоит
-- вообще.
--
-- Список неполный намеренно: настройки, которых здесь нет, показывают своё
-- родное описание. Дополнять его можно по одной строке.

local S = fgettext_ne

return {
	["3d_mode"] = S("Stereoscopic output for 3D glasses and split screens. Every mode except «none» draws the world twice and roughly halves the frame rate."),
	["3d_paralax_strength"] = S("How far apart the two eyes are in stereoscopic modes. Changes the depth effect, not the cost."),
	["ambient_occlusion_gamma"] = S("How dark the corners between blocks are. Shading is already computed, so the setting only changes how strongly it shows."),
	["anisotropic_filter"] = S("Keep textures sharp on surfaces seen at a steep angle, such as floors stretching into the distance. Costs a few percent of the frame on modern cards."),
	["antialiasing"] = S("How jagged edges are smoothed. FSAA is the most expensive and the cleanest; FXAA is nearly free and slightly blurry; «none» is fastest."),
	["arm_inertia"] = S("Let the held item lag behind the camera when you turn. Pure decoration, free."),
	["autosave_screensize"] = S("Remember the window size and whether it was maximised, and restore them at the next launch. No effect on performance."),
	["bilinear_filter"] = S("Smooth textures when they are magnified. Blurs the pixel art; the cost itself is negligible."),
	["connected_glass"] = S("Join neighbouring glass blocks into one surface, without the seam between them. Slightly fewer faces to draw."),
	["crosshair_alpha"] = S("How opaque the crosshair is. Zero hides it completely."),
	["crosshair_color"] = S("Colour of the crosshair."),
	["debanding"] = S("Add faint noise to break up the bands that appear in smooth gradients, such as the sky at dusk. Nearly free."),
	["directional_colored_fog"] = S("Tint the fog towards the colour of the sky in the direction you are looking. A small extra cost per frame."),
	["display_gamma"] = S("Brightness curve applied to the finished frame. Costs nothing, but a bright picture hides less than a dark one."),
	["enable_3d_clouds"] = S("Draw clouds as boxes instead of a flat layer. A little more to draw, and much better looking from below."),
	["enable_auto_exposure"] = S("Let the picture adapt to bright and dark places the way an eye does. Costs a pass that measures the frame's brightness."),
	["enable_bloom"] = S("Let bright surfaces bleed light into their surroundings. Costs several blur passes over the frame; the cost is fixed and does not depend on what is in view."),
	["enable_dynamic_shadows"] = S("Cast real shadows from the sun and moon. The most expensive effect in the game: the world is drawn again from the light's point of view, so expect to lose a noticeable part of the frame rate."),
	["enable_fog"] = S("Fade the world into fog at the edge of the view distance. Costs almost nothing and hides the boundary where the world stops being drawn."),
	["enable_post_processing"] = S("Master switch for effects applied to the finished frame: tone mapping, bloom, exposure, debanding. With it off, all of them stop costing anything."),
	["enable_raytraced_culling"] = S("Check visibility by tracing rays instead of guessing from the shape of the world. More accurate, so fewer hidden blocks are drawn, at the cost of some processor time."),
	["enable_translucent_foliage"] = S("Let light pass through leaves so they glow when the sun is behind them. A small extra cost wherever foliage is in view."),
	["enable_volumetric_clouds"] = S("Replace the flat cloud layer with clouds that have depth and can be flown through. Much more expensive than ordinary clouds: the sky is ray-marched every frame."),
	["enable_volumetric_lighting"] = S("Draw shafts of light through the air. Adds a pass and looks best against the sun; costs more the more of the screen the sky covers."),
	["enable_water_reflections"] = S("Reflect the sky and the world in water. Costs an extra pass wherever water is visible."),
	["enable_waving_leaves"] = S("Make leaves sway in the wind. The swaying is computed on the card for every leaf face in sight; noticeable in dense forest on weak hardware."),
	["enable_waving_plants"] = S("Make grass and plants sway. Same cost as waving leaves, spread over the ground rather than the canopy."),
	["enable_waving_water"] = S("Make the water surface rise and fall. Costs a little on the card and much more on the eye — still water reads as a flat sheet."),
	["exposure_compensation"] = S("Shift the whole picture brighter or darker, in stops. Free."),
	["fog_start"] = S("How far away the fog begins, as a share of the view distance. Starting it closer hides more of the world but does not make drawing cheaper — the blocks behind it are still there."),
	["fov"] = S("Field of view in degrees. A wider angle shows more of the world at once, which means more to draw: the cost grows roughly with the area brought into the frame."),
	["fps_max"] = S("Upper limit on frames per second. Frames above the limit are not drawn, so the card and processor idle instead of heating the room for nothing. Setting it above the refresh rate of the monitor gains nothing you can see."),
	["fps_max_unfocused"] = S("Frame limit while the window is not focused. Keep it low: a background window that draws hundreds of frames takes them away from whatever you are actually doing."),
	["fsaa"] = S("How many samples per pixel FSAA takes. Each step multiplies the work the card does on the world: 4× samples means roughly a quarter of the frame rate in the worst case."),
	["fullscreen"] = S("Run the game fullscreen instead of in a window. Usually a little faster than a window of the same size, because the desktop compositor steps out of the way."),
	["fxaa"] = S("Smooth edges by blurring them after the frame is drawn. Nearly free, but fine detail and text in the world become slightly soft."),
	["hurt_flash_enabled"] = S("Flash the screen red when you take damage. Free."),
	["leaves_style"] = S("How leaves are drawn. «Fancy» draws every face and looks like foliage; «simple» draws the outer faces only; «opaque» turns leaves into solid blocks and is the cheapest by a wide margin — a forest is where this setting is felt."),
	["mip_map"] = S("Keep smaller copies of every texture for distant surfaces. Costs a little video memory and usually pays it back: distant blocks stop shimmering and are cheaper to sample."),
	["node_highlighting"] = S("How the block under the crosshair is marked: an outline, a highlight, or nothing at all. The cost is negligible."),
	["occlusion_culler"] = S("How the engine decides which blocks are hidden behind others and can be skipped. Skipping them is what keeps caves and buildings cheap to draw."),
	["pause_on_lost_focus"] = S("Open the pause menu when the window loses focus. A single player game stops along with it, so the machine is freed for whatever you switched to."),
	["performance_tradeoffs"] = S("Trade some visual quality for speed in several places at once. Worth turning on if the frame rate matters more than the picture."),
	["screen_h"] = S("Height of the game window when it is not maximised or fullscreen. Like the width, it changes how many pixels have to be drawn each frame."),
	["screen_w"] = S("Width of the game window when it is not maximised or fullscreen. Costs nothing by itself: what costs is the number of pixels the card has to fill, so a wider window means a lower frame rate."),
	["screenshot_format"] = S("File format for screenshots. PNG keeps every pixel exactly; JPEG makes smaller files and loses fine detail."),
	["screenshot_path"] = S("Where screenshots are saved."),
	["screenshot_quality"] = S("JPEG quality, from crude to nearly lossless. Ignored for PNG."),
	["selectionbox_color"] = S("Colour of the selection outline."),
	["selectionbox_width"] = S("Thickness of the selection outline in pixels."),
	["shadow_filters"] = S("How shadow edges are softened. Each step samples the shadow map more times per pixel, so soft edges cost frames."),
	["shadow_map_color"] = S("Let coloured translucent blocks tint the shadow they cast. Requires a second shadow pass and is not cheap."),
	["shadow_map_max_distance"] = S("How far from the player shadows are still cast. Doubling the distance spreads the same shadow detail over four times the area, so shadows get coarser rather than slower."),
	["shadow_map_texture_32bit"] = S("Store the shadow map with more precision. Removes shadow acne and banding at the cost of twice the memory for the map."),
	["shadow_map_texture_size"] = S("Resolution of the shadow map. Sharper shadow edges cost video memory and time in square measure: doubling the number quadruples both."),
	["shadow_sky_body_orbit_tilt"] = S("Tilt of the sun's path across the sky. Changes where shadows fall, not what they cost."),
	["shadow_soft_radius"] = S("How wide the soft edge of a shadow is. Wider blur means more samples per pixel."),
	["shadow_strength_gamma"] = S("How dark the shadows are. Costs nothing once shadows are on."),
	["show_entity_selectionbox"] = S("Draw selection boxes around creatures and objects as well as blocks. Costs a few lines per visible object."),
	["smooth_lighting"] = S("Blend light across block corners instead of lighting each face flatly. Costs processor time when the world is meshed — that is, on loading and on every block you place — and nothing while merely looking around."),
	["soft_clouds"] = S("Soften the edges of the clouds. Costs almost nothing."),
	["tone_mapping"] = S("Compress the bright and dark ends of the frame the way film does, instead of clipping them. One extra pass over the picture."),
	["translucent_liquids"] = S("Make water and other liquids see-through. Costs a little: what is behind the surface has to be drawn as well."),
	["trilinear_filter"] = S("Smooth the transition between texture detail levels. Slightly more expensive than bilinear filtering and removes the visible seam where the levels change."),
	["undersampling"] = S("Draw the world at a fraction of the window resolution while keeping the interface sharp. A large gain in frame rate for a visibly coarser picture; 2 means a quarter of the pixels."),
	["view_bobbing_amount"] = S("How much the view sways while walking. Zero turns it off; some players find the sway unpleasant. Free either way."),
	["viewing_range"] = S("How far the world is drawn, in chunks of 16 blocks. The single most expensive graphics setting there is: the volume to load, keep in memory and draw grows with the cube of this number."),
	["volumetric_clouds_density"] = S("How thick the volumetric clouds are. Denser clouds end the ray sooner and are, if anything, slightly cheaper."),
	["volumetric_clouds_distance"] = S("How far volumetric clouds are traced. The single most expensive of the cloud settings: every extra step is more work per pixel of sky."),
	["volumetric_clouds_height"] = S("Height at which volumetric clouds float. Free."),
	["volumetric_clouds_pixel"] = S("Trace the clouds at a fraction of the screen resolution. The cheapest way to keep volumetric clouds at all on weak hardware: a coarser sky, a much lighter frame."),
	["volumetric_clouds_roundness"] = S("How rounded the cloud shapes are. Free."),
	["volumetric_clouds_size"] = S("Size of the cloud shapes. Free."),
	["volumetric_clouds_speed"] = S("How fast volumetric clouds drift. Free."),
	["volumetric_clouds_thickness"] = S("How deep the cloud layer is. Thicker layers take more steps to pass through and cost more."),
	["vsync"] = S("Wait for the monitor before showing a new frame. Removes tearing, but caps the frame rate at the refresh rate and adds a little input delay. Requires a restart, and the driver may enforce its own setting anyway."),
	["water_wave_height"] = S("How high the waves rise. Free — the wave is computed either way."),
	["water_wave_length"] = S("Distance between wave crests. Free."),
	["water_wave_speed"] = S("How fast the waves travel. Free."),
	["window_maximized"] = S("Whether the window opens maximised. Affects the frame rate only through the resulting window size."),
}
