local concat = table.concat
local insert = table.insert
local sprintf = string.format

local translation_file_header = [[
// This file is automatically generated
// It contains a bunch of fake gettext calls, to tell xgettext about the strings in config files
// To update it, refer to the bottom of builtin/common/settings/init.lua

fake_function() {]]

local function add_translation_string(result, str, seen)
	if seen[str] then
		return
	end
	seen[str] = true

	-- Prevent gettext from interpreting e.g. "50% of volume" as C-formatted string
	-- Documentation: https://www.gnu.org/software/gettext/manual/html_node/c_002dformat-Flag.html
	local force_no_c_format = str:find("%", 1, true)
	local prefix = force_no_c_format and "/* xgettext:no-c-format */ " or ""

	local have_newlines = str:find("\n", 1, true)
	if have_newlines then
		-- Formatting as "%q" inserts literal newlines. But we want '\n'.
		-- Hence, use "%s" and escape relevant characters manually.
		str = str:gsub("\n", "\\n")
		str = str:gsub("\"", "\\\"")
		insert(result, sprintf("\t%sgettext(\"%s\");", prefix, str))
	else
		insert(result, sprintf("\t%sgettext(%q);", prefix, str))
	end
end

local function create_translation_file(settings)
	local seen = {} -- to deduplicate entries
	local result = { translation_file_header }
	for _, entry in ipairs(settings) do
		if entry.type == "category" then
			add_translation_string(result, entry.name, seen)
		else
			if entry.readable_name then
				add_translation_string(result, entry.readable_name, seen)
			end
			if entry.comment ~= "" then
				add_translation_string(result, entry.comment, seen)
			end
		end
	end
	insert(result, "}\n")
	return concat(result, "\n")
end

-- The example configuration lives in config.example/ and is generated by
-- util/generate_settings_domains.py, which knows the file each setting belongs
-- into. This script only produces the translation file.

local file = assert(io.open("src/settings_translation_file.cpp", "w"))
-- For RUN_IN_PLACE the generated file may appear in the 'bin' folder, in which
-- case the line below has to be used instead.
--file = assert(io.open("settings_translation_file.cpp", "w"))
-- We don't want hidden settings to be translated, so we set read_all to false.
file:write(create_translation_file(settingtypes.parse_config_file(false, false)))
file:close()
