name: lua_lint

# Lint on lua changes on builtin or if workflow changed
on:
  workflow_dispatch:
  push:
    paths:
      - 'builtin/**.lua'
      - 'util/ci/**'
      - '.github/workflows/lua.yml'
  pull_request:
    paths:
      - 'builtin/**.lua'
      - 'util/ci/**'
      - '.github/workflows/lua.yml'

jobs:
  luacheck:
    name: "Builtin Luacheck and Unit Tests"
    runs-on: [self-hosted, linux, x64, public]

    steps:

    - uses: actions/checkout@v7
    - uses: leafo/gh-actions-lua@v13
      with:
        luaVersion: "5.1.5"
    - uses: leafo/gh-actions-luarocks@v6

    - name: Install LuaJIT
      run: ./util/ci/build_luajit.sh

    - name: Install luarocks tools
      run: |
        luarocks install --local luacheck
        luarocks install --local busted

    - name: Run checks (builtin)
      run: |
        $HOME/.luarocks/bin/luacheck builtin
        $HOME/.luarocks/bin/busted builtin
        $HOME/.luarocks/bin/busted builtin --lua=$HOME/LuaJIT/src/luajit

